Jackie0303
cdauber/collab3d pull request #14
Opened 2020-03-03 23:23 UTC by ThisIsJackieShi

Finished style changes

2020-03-04 03:41 UTC, OfekI requested changes

2020-03-04 03:41 UTC, OfekI commented on src/CommentsColumn/Comment/TopRow/ProfileIcon/ProfileIcon.js
> -  );
This component was perfectly fine the way it was before...
I see no reason not to just pass in the url into the `src` prop

2020-03-04 03:41 UTC, OfekI commented on src/CommentsColumn/Comment/TopRow/TopRow.js
> -      <ProfileIcon src={profilePic} author={author} />
All of the comment data is in `comments.js`. You can set the `profilePic` property there.

2020-03-04 03:41 UTC, OfekI commented on src/index.css
> -  left: calc(50% - (3 / 2) * (32px + 2 * 15px));
You should change this to `calc(50% - (3/2) * (16px + 2*8.5px))` to make sure it is centered (otherwise it puts the left edge in the center)

2020-03-04 03:41 UTC, OfekI commented on src/index.css
> +  width: 111px;
Generally it's better to set container heights with the sizes of their children or with padding and margin, I'd prefer not to have a hardcoded height and width for this

2020-03-04 03:41 UTC, OfekI commented on src/index.css
> +  color: #333333;
There was no reason to change this from `#333` to `#333333`, these are equivalent in CSS

2020-03-04 20:58 UTC, ThisIsJackieShi commented on src/CommentsColumn/Comment/TopRow/ProfileIcon/ProfileIcon.js
> -  );
I didn't understand the code correctly. Now i do, I think, I repushed my codes with changes.

2020-03-07 19:22 UTC, OfekI requested changes

2020-03-07 19:22 UTC, OfekI commented on src/CommentsColumn/Comment/Comment.css
> +  border-width: 0.1px 0px;
This can be done on one line, since only the bottom border needs to be styled
`border-bottom: 0.5px solid #c7c7c7`

2020-03-07 19:22 UTC, OfekI commented on src/comments.js
> +    src: "https://media-exp1.licdn.com/dms/image/C5103AQES2HWYu834NA/profile-displayphoto-shrink_200_200/0?e=1587600000&v=beta&t=e85cbE830lKu3L4wbpIqVu83o5byIKrhQx8pPpbpPbQ",
I'd rather name this `profilePicture: "..."` than `src: "..."`. `src` is kind of specific to `<img />` tags, whereas `profilePicture` describes what the property is.

2020-03-07 19:22 UTC, OfekI commented on src/index.css
> +img{
Since you're setting the width here, you don't need to set it up above for `.camera-button-icon-container`

2020-03-07 19:22 UTC, OfekI commented on src/index.css
> +  left: calc(50% - (3/2) * (16px + 2*8.5px));
Let's actually do `calc(50% - (3/2) * (14px + 2*8.5px))` so we use the width of the `<img />` and not the container `<div />`

2020-03-09 03:09 UTC, ThisIsJackieShi commented
fixed

2020-03-09 20:04 UTC, OfekI commented
> fixed

You wanna push up those fixes so I can re-review?

2020-03-10 19:01 UTC, OfekI approved these changes

2020-03-10 19:01 UTC, merged